[package]
name = "bla"
human_name = "Siksika"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.bla]
filename = "bla-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-bla"
platform = "windows"
uuid = "F2FDE58F-F454-4013-B4C4-1D3A1C48C9CF"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.bla"
package = "speller-bla"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-bla-mso"
platform = "windows"
uuid = "3E236262-98AA-4AC1-AB2B-AB82D0F9ED5D"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-bla"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
